services:
  eleganza:
    image: nginx:alpine
    container_name: eleganza
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eleganza.rule=Host(`eleganza.redcats.uk`)"
      - "traefik.http.routers.eleganza.entrypoints=websecure"
      - "traefik.http.routers.eleganza.tls=true"
      - "traefik.http.routers.eleganza.tls.certresolver=letsencrypt"
      - "traefik.http.services.eleganza.loadbalancer.server.port=80"

networks:
  web:
    external: true
